---
# GDS version 2.1

file_naming_conventions:

  rdacs:
    - ABOM
    - CMC
    - DMI
    - EUR IFR
    - JPL
    - METNO
    - MYO CMEMS
    - NAVO
    - NCEI
    - OSPO
    - OSISAF
    - REMSS
    - RSMAS
    - STAR
    - UKMO
    - ESACCI
    - JAXA
    - MAR
    - CMC
    - NCDC

  processing_levels:
    - L0
    - L1A
    - L1B
    - L2P
    - L3U
    - L3C
    - L3S
    - L4

  sst_types:
    - SSTint
    - SSTskin
    - SSTsubskin
    - SSTdepth
    - SSTfnd
    - SSTblend

  file_types:
    - nc
    - xml


global_attributes:

  - Conventions:
      allowed_types:
        - str
      mandatory: true
  - title:
      allowed_types:
        - str
      mandatory: true
  - summary:
      allowed_types:
        - str
      mandatory: true
  - references:
      allowed_types:
        - str
      mandatory: true
  - institution:
      allowed_types:
        - str
      mandatory: true
  - history:
      allowed_types:
        - str
      mandatory: true
  - comment:
      allowed_types:
        - str
      mandatory: true
  - license:
      allowed_types:
        - str
      mandatory: true
  - id:
      allowed_types:
        - str
      mandatory: true
  - naming_authority:
      allowed_types:
        - str
      mandatory: true
  - product_version:
      allowed_types:
        - str
      mandatory: true
  - uuid:
      allowed_types:
        - str
      mandatory: true
  - gds_version_id:
      allowed_types:
        - str
      mandatory: true
  - netcdf_version_id:
      allowed_types:
        - str
      mandatory: true
  - date_created:
      allowed_types:
        - date
      mandatory: true

  - date_modified:
      allowed_types:
        - date
      mandatory: false
  - date_issued:
      allowed_types:
        - date
      mandatory: false
  - date_metadata_modified:
      allowed_types:
        - date
      mandatory: false

  - file_quality_level:
      allowed_types:
        - int32
      mandatory: true
  - spatial_resolution:
      allowed_types:
        - str
      mandatory: true
  - time_coverage_start:
      allowed_types:
        - date
      mandatory: true
  - time_coverage_end:
      allowed_types:
        - date
      mandatory: true
  - instrument:
      allowed_types:
        - str
      mandatory: true
      allowed_values:
        - AMSRE
        - AATSR
        - ATSR
        - AVHRR_GAC
        - AVHRR_LAC
        - AVHRR
        - GOES_Imager
        - MODIS
        - JAMI
        - AVHRR_HRPT
        - SEVIRI
        - TMI
        - SLSTR
  - instrument_vocabulary:
      allowed_types:
        - str
      mandatory: true
      allowed_values:
        - CEOS instrument table
  - metadata_link:
      allowed_types:
        - str
      mandatory: true
  - keywords:
      allowed_types:
        - str
      mandatory: true
  - keywords_vocabulary:
      allowed_types:
        - str
      mandatory: true
      allowed_values:
        - "NASA Global Change Master Directory (GCMD) Science Keywords"
  - standard_name_vocabulary:
      allowed_types:
        - str
      mandatory: true
  - geospatial_lat_min:
      allowed_types:
        - float32
        - float64
      mandatory: true
  - geospatial_lat_max:
      allowed_types:
        - float32
        - float64
      mandatory: true
  - geospatial_lat_units:
      allowed_types:
        - str
      mandatory: true
      allowed_values:
        - degrees_north
  - geospatial_lat_resolution:
      allowed_types:
        - float32
        - float64
      mandatory: true
  - geospatial_lon_min:
      allowed_types:
        - float32
        - float64
      mandatory: true
  - geospatial_lon_max:
      allowed_types:
        - float32
        - float64
      mandatory: true
  - geospatial_lon_units:
      allowed_types:
        - str
      mandatory: true
      allowed_values:
        - degrees_east
  - geospatial_lon_resolution:
      allowed_types:
        - float32
        - float64
      mandatory: true

  - geospatial_vertical_min:
      allowed_types:
        - float32
        - float64
      mandatory: false
  - geospatial_vertical_max:
      allowed_types:
        - float32
        - float64
      mandatory: false
  - geospatial_vertical_resolution:
      allowed_types:
        - float32
        - float64
      mandatory: false
  - geospatial_vertical_units:
      allowed_types:
        - str
      mandatory: false
      allowed_values:
        - meters
        - m
  - geospatial_vertical_positive:
      allowed_types:
        - str
      mandatory: false
      allowed_values:
        - up
        - down

  - geospatial_bounds:
      allowed_types:
        - str
      mandatory: true

  - geospatial_bounds_crs:
      allowed_types:
        - str
      mandatory: false
  - geospatial_bounds_vertical_crs:
      allowed_types:
        - str
      mandatory: false

  - acknowledgment:
      allowed_types:
        - str
      mandatory: true

  - creator_name:
      allowed_types:
        - str
      mandatory: false
  - creator_url:
      allowed_types:
        - url
      mandatory: false
  - creator_email:
      allowed_types:
        - str
      mandatory: false
  - creator_type:
      allowed_types:
        - str
      mandatory: false
      allowed_values:
        - person
        - group
        - institution
        - position
  - creator_institution:
      allowed_types:
        - str
      mandatory: false

  - project:
      allowed_types:
        - str
      mandatory: true

  - program:
      allowed_types:
        - str
      mandatory: false
  - contributor_name:
      allowed_types:
        - str
      mandatory: false
  - contributor_role:
      allowed_types:
        - str
      mandatory: false

  - publisher_name:
      allowed_types:
        - str
      mandatory: true
  - publisher_url:
      allowed_types:
        - url
      mandatory: true
  - publisher_email:
      allowed_types:
        - str
      mandatory: true

  - publisher_type:
      allowed_types:
        - str
      mandatory: false
      allowed_values:
        - person
        - group
        - institution
        - position
  - publisher_institution:
      allowed_types:
        - str
      mandatory: false

  - processing_level:
      allowed_types:
        - str
      mandatory: true
      allowed_values:
        - L2P
        - L3C
        - L3U
        - L3S
        - L4
        - GMPE
  - cdm_data_type:
      allowed_types:
        - str
      mandatory: true
      allowed_values:
        - swath
        - grid


  - start_time:
      deprecated: true
  - stop_time:
      deprecated: true
  - northernmost_latitude:
      deprecated: true
  - southernmost_latitude:
      deprecated: true
  - easternmost_longitude:
      deprecated: true
  - westernmost_longitude:
      deprecated: true
  - sensor:
      deprecated: true


longitude:
  valid_min: -180
  valid_max: 180
